### PR TITLE
Fixing calls to Number.isNaN and 'NaN' displaying on the page

### PR DESCRIPTION
**Pull request by dprensha**

### CODE REVIEW

**Comment by dprensha** [comment]
fixes #11
fixes #13

**Comment by edjw** [comment]
Hi thanks for this. Does the site still work‽ Very unmaintained! What's the URL?

**Comment by edjw** [comment]
Ok URL is on the repo

**Comment by dprensha** [comment]
@edjw Yes still is running! I actually downloaded the app on my phone and use it daily. Very useful!! Very interested in adding more features of you're interested

**Comment by edjw** [comment]
@dprensha Ok great! Are you affected by #13 at all?

I don't see an error on this aeropress page which sounds like is the problem on #11 
https://coffee-coach.netlify.app/aeropress-by-hasbean

**Comment by dprensha** [comment]
@edjw 
> @dprensha Ok great! Are you affected by #13 at all?

Yes, this PR should fix that issue as well

**Comment by dprensha** [comment]
With the aeropress page, the page loaded but the water dilution amount said "NaN" in the UI. That was a separate issue but this PR also fixes that.

**Comment by edjw** [comment]
Merged. Seems to be working fine now. Thanks for this :-)

**Comment by edjw** [comment]
@dprensha 

> Very interested in adding more features of you're interested

Which features were you interested in adding? I'm happy for you to fork and carry on there if you prefer. I found a few things looking at this in the last few days

https://github.com/edjw/Coffee-Coach/issues

**Comment by dprensha** [comment]
@edjw 

> Which features were you interested in adding? I'm happy for you to fork and carry on there if you prefer. I found a few things looking at this in the last few days

I was thinking of adding a couple of recipes, definitely some cupping recipe, perhaps the SCA standard one, not sure yet.  I can also look into those issues you mentioned as well.

**Comment by edjw** [comment]
Sure go for it :-)

**Pull request merged**
